# Generated by Django 4.2.11 on 2024-06-01 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 19, 27, 15, 480949)),
        ),
    ]
