# Generated by Django 4.2.11 on 2024-06-02 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_alter_tournament_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 16, 47, 57, 98310)),
        ),
    ]
