# Generated by Django 4.2.11 on 2024-06-11 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_alter_tournament_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 18, 51, 9, 677114)),
        ),
    ]
