MAX_PADDLE_Y = 27
MIN_PADDLE_Y = -27
PADDLE_X = 54

SCREEN_WIDTH = 700
SCREEN_HEIGHT = 450

SCREEN_CENTER = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)

BUTTON_COLOR = (0, 0, 0)

PADDLE_WIDTH = 10
PADDLE_HEIGHT = 50

REFRESH_RATE = 0.01
MOVSPEED = 0.7
BALL_WIDTH = 10
BALL_HEIGHT = 10

MAX_BALL_X = SCREEN_WIDTH - PADDLE_WIDTH - BALL_WIDTH
MAX_BALL_Y = SCREEN_HEIGHT - BALL_HEIGHT
INITIAL_STATE = {
    "player_one": {"x": -PADDLE_X, "y": 0, "score": 0,},
    "player_two": {"x": PADDLE_X, "y": 0, "score": 0,},
    "ball": {"x": 0, "y": 0,},
}